"""Seed data for SKR03 accounts, system sources, and system user."""

from app.models.skr03 import AccountCategory

# System user for Local Mode (deterministic UUID, matches deps.py and frontend)
SYSTEM_USER_ID = "00000000-0000-0000-0000-000000000000"

# Curated SKR03 accounts for e-commerce bookkeeping
# Format: (account_number, name, category, bu_schluessel)
# BU-Schlüssel: 2=7%USt, 3=19%USt, 8=7%VSt, 9=19%VSt, None=no VAT
SKR03_ACCOUNTS = [
    # Revenue accounts (Kontenklasse 8)
    (8400, "Erlöse 19% USt", AccountCategory.REVENUE, 3),
    (8300, "Erlöse 7% USt", AccountCategory.REVENUE, 2),
    (8120, "Steuerfreie Ausfuhrlieferungen Drittland", AccountCategory.REVENUE, None),
    (8125, "Steuerfreie innergemeinschaftliche Lieferungen", AccountCategory.REVENUE, None),
    (8195, "Erlöse als Kleinunternehmer §19 UStG", AccountCategory.REVENUE, None),
    (8736, "Gewährte Skonti 19% USt", AccountCategory.REVENUE, 3),
    (8720, "Erlösschmälerungen 19% USt", AccountCategory.REVENUE, 3),
    # Expense accounts — goods & materials (Kontenklasse 3)
    (3400, "Wareneingang 19% Vorsteuer", AccountCategory.EXPENSE, 9),
    (3300, "Wareneingang 7% Vorsteuer", AccountCategory.EXPENSE, 8),
    # Expense accounts — shipping & logistics
    (4710, "Verpackungsmaterial", AccountCategory.EXPENSE, 9),
    (4730, "Ausgangsfrachten / Versandkosten", AccountCategory.EXPENSE, 9),
    (4750, "Transportversicherung", AccountCategory.EXPENSE, None),
    (4910, "Porto", AccountCategory.EXPENSE, None),
    # Expense accounts — office & IT
    (4925, "Telefax und Internetkosten", AccountCategory.EXPENSE, 9),
    (4920, "Telefon", AccountCategory.EXPENSE, 9),
    (4930, "Bürobedarf", AccountCategory.EXPENSE, 9),
    (4940, "Zeitschriften, Bücher (Fachliteratur)", AccountCategory.EXPENSE, 8),
    (4806, "Wartungskosten für Hard- und Software", AccountCategory.EXPENSE, 9),
    # Expense accounts — marketing & sales
    (4600, "Werbekosten", AccountCategory.EXPENSE, 9),
    (4605, "Streuartikel", AccountCategory.EXPENSE, 9),
    (4760, "Verkaufsprovisionen", AccountCategory.EXPENSE, 9),
    # Expense accounts — platform fees (individuelle Konten unter 4760)
    (4761, "Etsy Gebühren", AccountCategory.EXPENSE, 9),
    (4762, "Amazon Gebühren", AccountCategory.EXPENSE, 9),
    (4763, "Shopify Gebühren", AccountCategory.EXPENSE, 9),
    (4764, "Stripe Gebühren", AccountCategory.EXPENSE, 9),
    (4765, "PayPal Gebühren", AccountCategory.EXPENSE, 9),
    # Expense accounts — operations
    (4650, "Bewirtungskosten", AccountCategory.EXPENSE, 9),
    (4805, "Reparaturen und Instandhaltung BGA", AccountCategory.EXPENSE, 9),
    (4900, "Sonstige betriebliche Aufwendungen", AccountCategory.EXPENSE, 9),
    (4970, "Nebenkosten des Geldverkehrs", AccountCategory.EXPENSE, None),
    (4855, "Sofortabschreibung GWG", AccountCategory.EXPENSE, None),
    # Expense accounts — insurance & fees
    (4360, "Versicherungen", AccountCategory.EXPENSE, None),
    (4320, "Gewerbesteuer", AccountCategory.EXPENSE, None),
    (4380, "Beiträge", AccountCategory.EXPENSE, None),
    # Expense accounts — professional services
    (4955, "Buchführungskosten", AccountCategory.EXPENSE, 9),
    (4950, "Rechts- und Beratungskosten", AccountCategory.EXPENSE, 9),
    # Neutral accounts — private
    (1800, "Privatentnahmen allgemein", AccountCategory.NEUTRAL, None),
    (1890, "Privateinlagen", AccountCategory.NEUTRAL, None),
    # Neutral accounts — bank & clearing
    (1200, "Bank", AccountCategory.NEUTRAL, None),
    (1360, "Geldtransit", AccountCategory.NEUTRAL, None),
    (1590, "Durchlaufende Posten", AccountCategory.NEUTRAL, None),
    # Marketplace virtual bank accounts (D4: 12xx range)
    (1201, "Verrechnungskonto Etsy Payments", AccountCategory.NEUTRAL, None),
    (1202, "Verrechnungskonto Amazon Payments", AccountCategory.NEUTRAL, None),
    (1203, "Verrechnungskonto Shopify Payments", AccountCategory.NEUTRAL, None),
    (1204, "Verrechnungskonto Stripe", AccountCategory.NEUTRAL, None),
    (1210, "Verrechnungskonto PayPal", AccountCategory.NEUTRAL, None),
    # §13b Reverse Charge accounts (D7: Automatik-Konten)
    (3125, "Leistungen §13b UStG mit Vorsteuerabzug", AccountCategory.EXPENSE, 94),  # BU 94, Regelbesteuert
    (3165, "Leistungen §13b UStG ohne Vorsteuerabzug", AccountCategory.EXPENSE, 95),  # BU 95, Kleinunternehmer
    (1787, "Umsatzsteuer nach §13b UStG 19%", AccountCategory.NEUTRAL, None),  # Auto-generated by 3125/3165
]

# Migration mapping: old_id → new_id for accounts that changed numbers
# Used by Alembic migration to remap receipt_line_items and accounting_patterns
SKR03_MIGRATION_MAP = {
    8337: 8195,  # Kleinunternehmer (was Reverse Charge account)
    8742: 8720,  # Erlösschmälerungen 19% USt
    3560: 4710,  # Verpackungsmaterial
    3565: 4900,  # Verpackungslizenz → Sonstige betriebl. Aufwendungen
    4930: 4730,  # Versandkosten → Ausgangsfrachten (4930 is now Bürobedarf)
    4970: 4910,  # Porto (4970 is now Nebenkosten Geldverkehr)
    4980: 4750,  # Transportversicherung
    4910: 4925,  # Internetkosten → Telefax und Internetkosten
    4360: 4805,  # Reparaturen BGA (4360 is now Versicherungen)
    4855: 4970,  # Nebenkosten Geldverkehr (4855 is now GWG)
    4390: 4360,  # Betriebliche Versicherungen (4390 is now Beiträge)
    4510: 4320,  # Gewerbesteuer (4510 is now Kfz-Steuern)
    6560: 4930,  # Büromaterial → Bürobedarf
    6570: 4930,  # Druckerpatronen → Bürobedarf
    6800: 4600,  # Werbekosten
    6805: 4605,  # Streuartikel
    6815: 4760,  # Verkaufsprovisionen
    6820: 4600,  # Messe-/Ausstellungskosten → Werbekosten
    6830: 4761,  # Etsy Gebühren
    6831: 4762,  # Amazon Gebühren
    6832: 4763,  # Shopify Gebühren
    6833: 4764,  # Stripe Gebühren
    6834: 4765,  # PayPal Gebühren
    6300: 4900,  # Sonstige betriebl. Aufwendungen
}


def seed_skr03_accounts(session) -> int:
    """Insert or update SKR03 seed accounts. Returns number of accounts inserted."""
    from app.models.skr03 import SKR03Account

    inserted = 0
    for account_number, name, category, bu_schluessel in SKR03_ACCOUNTS:
        existing = session.get(SKR03Account, account_number)
        if existing is None:
            session.add(
                SKR03Account(
                    id=account_number,
                    name=name,
                    category=category,
                    bu_schluessel=bu_schluessel,
                    is_system=True,
                )
            )
            inserted += 1
        else:
            # Update existing accounts with bu_schluessel if not set
            if existing.bu_schluessel is None and bu_schluessel is not None:
                existing.bu_schluessel = bu_schluessel
            # Ensure system flag is set on all seed accounts
            if not existing.is_system:
                existing.is_system = True
    session.commit()
    return inserted


def seed_site_settings(session) -> bool:
    """Ensure a SiteSettings row exists. Returns True if created."""
    from app.models.site_settings import SiteSettings

    existing = session.get(SiteSettings, 1)
    if existing is None:
        session.add(SiteSettings(id=1))
        session.commit()
        return True
    return False


def seed_system_user(session) -> bool:
    """Ensure system user exists for Local Mode. Returns True if created.

    The system user (ID: 00000000-...) is used in Local Mode to satisfy FK
    constraints on transactions, receipts, etc. Protected from deletion.
    """
    from app.models.user import User

    existing = session.get(User, SYSTEM_USER_ID)
    if existing is None:
        session.add(
            User(
                id=SYSTEM_USER_ID,
                provider_id="local",
                provider_type="local",
                email="local@localhost",
                name="Local User",
            )
        )
        session.commit()
        return True
    return False


# System sources with deterministic UUIDs (stable across environments)
# These are seeded as user_id=NULL (system sources)
# Format: (id, name, type, check_account_id, source_config)
# Check accounts: Virtual bank accounts per D4/D9 (12xx range)
# source_config: marketplace-specific settings (D3: has_ust_id_registered, vat_id)
SYSTEM_SOURCES = [
    (
        "a0000000-0000-0000-0000-000000000001",
        "Etsy",
        "marketplace_mapping",
        1201,
        {"has_ust_id_registered": True, "vat_id": "IE9777587C", "parser": "etsy"},
    ),
    (
        "a0000000-0000-0000-0000-000000000002",
        "Amazon",
        "marketplace_mapping",
        1202,
        {"has_ust_id_registered": True, "vat_id": "LU20260743", "parser": "amazon"},
    ),
    (
        "a0000000-0000-0000-0000-000000000003",
        "Shopify",
        "marketplace_mapping",
        1203,
        {"has_ust_id_registered": True, "vat_id": "IE3347697KH", "parser": "shopify"},
    ),
    (
        "a0000000-0000-0000-0000-000000000004",
        "Stripe",
        "marketplace_mapping",
        1204,
        {"has_ust_id_registered": True, "vat_id": "IE3396855EH", "parser": "stripe"},
    ),
    ("a0000000-0000-0000-0000-000000000005", "PayPal", "api_sync", 1210, {"has_ust_id_registered": True, "vat_id": "LU22046007"}),
]


def seed_system_sources(session) -> int:
    """Insert system sources if they don't exist. Returns number inserted."""

    from app.models.source import SourceType, TransactionSourceConfig

    inserted = 0
    for source_id, name, source_type, check_account_id, source_config in SYSTEM_SOURCES:
        existing = session.get(TransactionSourceConfig, source_id)
        if existing is None:
            session.add(
                TransactionSourceConfig(
                    id=source_id,
                    user_id=None,
                    name=name,
                    type=SourceType(source_type),
                    check_account_id=check_account_id,
                    source_config=source_config,
                )
            )
            inserted += 1
        else:
            # Update type and check_account_id if they changed
            if existing.type.value != source_type:
                existing.type = SourceType(source_type)
            if existing.check_account_id != check_account_id:
                existing.check_account_id = check_account_id
            # Update source_config if not set or if new config has more keys
            if existing.source_config is None or (source_config and len(source_config) > len(existing.source_config or {})):
                existing.source_config = source_config
    session.commit()
    return inserted


def seed_oms_providers(session) -> bool:
    """Auto-configure the Billbee OMS provider from environment. Returns True if created.

    Fallback for the migration seed: if Billbee credentials are present but no
    provider record exists (e.g. a DB restored before the migration), create it.
    """
    from sqlalchemy import select

    from app.config import get_settings
    from app.models.oms_provider import OmsProviderRecord, OmsProviderType

    if not get_settings().billbee_api_key:
        return False

    existing = session.scalar(select(OmsProviderRecord).where(OmsProviderRecord.type == OmsProviderType.BILLBEE))
    if existing is not None:
        return False

    session.add(OmsProviderRecord(type=OmsProviderType.BILLBEE, display_name="Billbee", is_active=True))
    session.commit()
    return True
