"""add rc_tax_rate to site_settings

Revision ID: 7f213138fc75
Revises: 29bc6f86ac1a
Create Date: 2026-03-01 21:17:06.791180

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f213138fc75"
down_revision: Union[str, Sequence[str], None] = "29bc6f86ac1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("site_settings", sa.Column("rc_tax_rate", sa.Numeric(precision=5, scale=4), server_default="0.1900", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site_settings", "rc_tax_rate")
    # ### end Alembic commands ###
