"""add_is_system_to_skr03_accounts

Revision ID: 80d57cbda001
Revises: 850978e6e8b0
Create Date: 2026-02-24 20:35:29.911844

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80d57cbda001"
down_revision: Union[str, Sequence[str], None] = "850978e6e8b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("skr03_accounts", sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False))

    # Mark existing seed accounts as system accounts
    # WARNING: These 41 IDs are duplicated from app/seed.py:SKR03_ACCOUNTS
    # If you add/remove accounts in seed.py, this migration won't retroactively update them.
    # New accounts added to seed.py will be marked is_system=True via seed_skr03_accounts().
    # This duplication is intentional: migration captures the accounts at this point in time.
    seed_account_ids = [
        8400,
        8300,
        8120,
        8125,
        8195,
        8736,
        8720,  # Revenue
        3400,
        3300,  # Goods
        4710,
        4730,
        4750,
        4910,  # Shipping
        4925,
        4920,
        4930,
        4940,
        4806,  # Office/IT
        4600,
        4605,
        4760,  # Marketing
        4761,
        4762,
        4763,
        4764,
        4765,  # Platform fees
        4650,
        4805,
        4900,
        4970,
        4855,  # Operations
        4360,
        4320,
        4380,  # Insurance/fees
        4955,
        4950,  # Professional services
        1800,
        1890,  # Private
        1200,
        1360,
        1590,  # Bank/clearing
    ]
    op.execute(sa.text(f"UPDATE skr03_accounts SET is_system = true WHERE id IN ({','.join(str(i) for i in seed_account_ids)})"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skr03_accounts", "is_system")
    # ### end Alembic commands ###
