"""add export_format to export_logs

Revision ID: 850978e6e8b0
Revises: 0001_initial
Create Date: 2026-02-24 18:20:11.812304

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "850978e6e8b0"
down_revision: Union[str, Sequence[str], None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("export_logs", sa.Column("export_format", sa.String(length=20), nullable=False, server_default="buchungsstapel"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("export_logs", "export_format")
    # ### end Alembic commands ###
