"""add billbee sync label setting

Revision ID: a72bcdd546cf
Revises: b533aa7c2c7e
Create Date: 2026-03-05 17:06:34.134219

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a72bcdd546cf"
down_revision: Union[str, Sequence[str], None] = "b533aa7c2c7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("site_settings", sa.Column("billbee_sync_set_labels", sa.Boolean(), server_default="true", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("site_settings", "billbee_sync_set_labels")
    # ### end Alembic commands ###
