"""add rc_tax_rate to receipt_line_items

Revision ID: fad56dbed22a
Revises: 7f213138fc75
Create Date: 2026-03-01 21:19:24.690372

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fad56dbed22a"
down_revision: Union[str, Sequence[str], None] = "7f213138fc75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipt_line_items", sa.Column("rc_tax_rate", sa.Numeric(precision=5, scale=4), nullable=True))
    # Backfill: Legacy RC items get 0.19 (what they implicitly had)
    op.execute("""
        UPDATE receipt_line_items
        SET rc_tax_rate = 0.1900
        WHERE tax_rule::text LIKE 'rc_%' OR tax_rule::text = 'reverse_charge'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("receipt_line_items", "rc_tax_rate")
    # ### end Alembic commands ###
